---
apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    app: pl-predictor
    component: queue
spec:
  type: ClusterIP
  selector:
    app: pl-predictor
    component: queue
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
...