---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
  - name: database-init
    files:
      - init/01_init_schema.sql
      - init/02_add_jobs.sql
      - init/03_add_job_status_constraint.sql
generatorOptions:
  disableNameSuffixHash: true
...